version: '2.1'

services:
  blueboard-chat-service:
    image: blueboard-chat-service
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 config.js